### ISSUE TITLE
Fails to load on Joyent Cloud Server

### ISSUE THREAD

**Issue by deepwell** [NodeFly/NodeFly#1]
Steps to reproduce:

Add nodefly to package.json:
"nodefly": "stable" 

Deploy code to Joyent server:
$ git push joyent

{snip}
remote:     make: Entering directory `/home/node/local/lib/node_modules/nodefly/node_modules/timekit/build'
remote:       CXX(target) Release/obj.target/timekit/src/profiler.o
remote:     cc1plus: error: unrecognized command line option "-fno-tree-vrp"
remote:     make: *** [Release/obj.target/timekit/src/profiler.o] Error 1
remote:     make: Leaving directory`/home/node/local/lib/node_modules/nodefly/node_modules/timekit/build'
remote:     gyp ERR! build error 
remote:     gyp ERR! stack Error: `make` failed with exit code: 2
remote:     gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/v0.8.8/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)
remote:     gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
remote:     gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
remote:     gyp ERR! System SunOS 5.11
remote:     gyp ERR! command "node" "/opt/nodejs/v0.8.8/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:     gyp ERR! cwd /home/node/local/lib/node_modules/nodefly/node_modules/timekit
remote:     gyp ERR! node -v v0.8.8
remote:     gyp ERR! node-gyp -v v0.6.7
remote:     gyp ERR! not ok 
remote:     npm WARN optional dep failed, continuing timekit@0.1.8

{snip}
remote:     > node server.js
remote:  
remote:  
remote:     module.js:340
remote:         throw err;
remote:               ^
remote:     Error: Cannot find module './compiled/solaris/ia32/v0.8.12/gcinfo'
remote:         at Function.Module._resolveFilename (module.js:338:15)
remote:         at Function.Module._load (module.js:280:25)
remote:         at Module.require (module.js:362:17)
remote:         at require (module.js:378:17)
remote:         at Object.<anonymous> (/home/node/local/lib/node_modules/nodefly/node_modules/nodefly-gcinfo/index.js:57:18)
remote:         at Module._compile (module.js:449:26)
remote:         at Object.Module._extensions..js (module.js:467:10)
remote:         at Module.load (module.js:356:32)
remote:         at Function.Module._load (module.js:312:12)
remote:         at Module.require (module.js:362:17)
remote:  
remote:     npm ERR! prod@1.0.0 start: `node server.js`
remote:     npm ERR! `sh "-c" "node server.js"` failed with 1
remote:     npm ERR! 
remote:     npm ERR! Failed at the prod@1.0.0 start script.
remote:     npm ERR! This is most likely a problem with the prod package,
remote:     npm ERR! not with npm itself.
remote:     npm ERR! Tell the author that this fails on your system:
remote:     npm ERR!     node server.js
remote:     npm ERR! You can get their info via:
remote:     npm ERR!     npm owner ls prod
remote:     npm ERR! There is likely additional logging output above.
remote:     npm ERR! 
remote:     npm ERR! System SunOS 5.11
remote:     npm ERR! command "/opt/nodejs/v0.6/bin/node" "/opt/nodejs/bin/npm" "start" "--node-version" "v0.8.8"

I checked on the server and in the compiled directory, there is no "solaris" directory instead it was called "sunos".

**Comment by groundwater** [comment]
Hi, I have just pushed a change to our `nodefly-gcinfo` module to handle this case. Please try again.

**Comment by deepwell** [comment]
Nice quick work, thanks!
