### ISSUE TITLE
Top Functions Misleading

### ISSUE THREAD

**Issue by xjamundx** [NodeFly/NodeFly#10]
With the widget called "Top Functions" I assumed I'd be seeing function names new relic style, but instead it just appears to give me express routes.

**Comment by prawnsalad** [comment]
+1 on this. I was all excited to see my most used methods until I realised it's just HTTP calls :(

**Comment by themitchy** [comment]
We're still fleshing this out, but we will have a way to let you instrument any function and see it reported on the NodeFly dashboard.

**Comment by xjamundx** [comment]
Call it "top routes". Save "functions" for when you figure out how to do flame graphs like joyent produces.
