### ISSUE TITLE
dashboard is broken (CORS issue?)

### ISSUE THREAD

**Issue by troygoode** [NodeFly/NodeFly#11]
My dashboard won't load at all today.

![Screen Shot 2013-01-21 at 9 27 22 AM](https://f.cloud.github.com/assets/72844/83233/bf049b1e-63d6-11e2-8787-397b7522bdd7.png)

**Comment by DaveYVR** [comment]
Seems to have been the result of temporary network issues that have been resolved.

**Comment by prawnsalad** [comment]
Although it's closed, this issue happens due to loading data via HTTPS when on a HTTP page. The same issue has just happened to me and I thought the service was broken.

Perhaps have the dashboard only accessible via HTTPS?

**Comment by ricardobeat** [comment]
Just signed up manually after heroku addons failed, everything is broken. I'm getting the same 'Origin is not allowed' error.
