### ISSUE TITLE
nodefly npm lib not on github

### ISSUE THREAD

**Issue by Almad** [NodeFly/NodeFly#12]
This is strange as it is opensource anyways.

**Comment by groundwater** [comment]
Hi @almad this is definitely on our roadmap. 

The original repository was combined the server and agent together. We are in the process of publishing a clean repo for the agent.

**Comment by andyburke** [comment]
+1 for this, I would like to submit a patch for #14

**Comment by bjornstar** [comment]
+1 Would love to submit patches. Any progress on this?

**Comment by sprice** [comment]
@jacobgroundwater This would be nice. You're currently publishing the `nodefly` package to npm. I see it was last updated 2 days ago. Why not make the repo of this project public while you continue to work on it?

At the moment users cannot fork this project to add individual fixes, or to create pull requests back to you, thereby speeding up your development. This isn't a good thing.

**Comment by groundwater** [comment]
@sprice I have actually departed from NodeFly. I believe someone else may come in, but I thought I would let you know I won't be addressing this.

**Comment by sprice** [comment]
@jacobgroundwater thanks for the update.

I'll ping @themitchy since he's the only member I see of the NodeFly GitHub organization.

**Comment by andyburke** [comment]
Is NodeFly dead?

**Comment by themitchy** [comment]
@sprice,  we have not yet made the repo public.  We look forward to working with the community and think it will be a big benefit to us when we are ready for those contributions.  Just not quite yet.

@andyburke, I have checked with my physician;  He assures me I am alive and well. The rest of the team looks healthy too.  Thank you for your concern for our well being.  Should the situation change, I will endeavour to be the best zombie-developer I can be.

**Comment by sprice** [comment]
@themitchy why is this issue now closed? The repo still isn't open source.
