### ISSUE TITLE
 Concurrent Connections + throughput

### ISSUE THREAD

**Issue by prawnsalad** [NodeFly/NodeFly#15]
Where is the concurrent connections and throughput stats coming from? I was expecting the number of network connections in my websocket (socket.io) app to appear with the traffic throughput but nothing appeared.

**Comment by themitchy** [comment]
Right now these stats are generated off of connections to an HTTPServer object.  We will be doing some lower level stuff and we will also be doing some socket.io-specific stuff in the future.
