### ISSUE TITLE
Instrument the request module

### ISSUE THREAD

**Issue by xjamundx** [NodeFly/NodeFly#16]
Hey guys,

Maybe you do this already, but I didn't  notice it.

Can you automatically instrument all requests made with the `request` module? It is the primary way people make HTTP requests on node and would be super helpful.

**Comment by themitchy** [comment]
Hey @xjamundx,

We had been instrumenting the http.ClientRequest class directly but there was an issue that would have stopped it working with the request module.  Thanks for bringing it up!  nodefly@0.1.25 should work for anyone using that module for outgoing http now.
