### ISSUE TITLE
Crash on Joyent Cloud Server

### ISSUE THREAD

**Issue by deepwell** [NodeFly/NodeFly#2]
Nodefly causes server process to crash after being up for a few seconds.

/home/node/local/lib/node_modules/nodefly/lib/tiers.js:15
        data._ts = nf.millis();
                      ^
TypeError: Cannot call method 'millis' of undefined
    at Timer.<anonymous> (/home/node/local/lib/node_modules/nodefly/lib/tiers.js:15:16)
    at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)

npm ERR! prod@1.0.0 start: `node server.js`
npm ERR! `sh "-c" "node server.js"` failed with 1
npm ERR! 
npm ERR! Failed at the prod@1.0.0 start script.
npm ERR! This is most likely a problem with the prod package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls prod
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System SunOS 5.11
npm ERR! command "/opt/nodejs/v0.6/bin/node" "/opt/nodejs/bin/npm" "start" "--node-version" "v0.8.8"
npm ERR! cwd /home/node/node-service/releases/2012-11-08T20-35-03.190873764
npm ERR! node -v v0.6.8
npm ERR! npm -v 1.1.0-2
npm ERR! code ELIFECYCLE
npm ERR! message prod@1.0.0 start: `node server.js`
npm ERR! message `sh "-c" "node server.js"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/node/node-service/releases/2012-11-08T20-35-03.190873764/npm-debug.log
npm not ok
failed

**Comment by groundwater** [comment]
Hi @deepwell this looks like a serious error. Can you include the machine image you are using on Joyent? We will attempt to reproduce the error and fix it as soon as possible.

**Comment by deepwell** [comment]
Sure, the image is sdc:sdc:nodejs:1.3.3.

I upgraded node.js to 0.8.8.

**Comment by groundwater** [comment]
Hi, I have updated the nodefly agent. Please try installing `nodefly@0.1.9` - if that works for you I will mark the fix as stable in npm.

**Comment by deepwell** [comment]
Looks like that fixes it, thanks again.
