### ISSUE TITLE
node v0.10 support

### ISSUE THREAD

**Issue by bjornstar** [NodeFly/NodeFly#20]
I updated to v0.10 today, nodefly now gives an error stating:

Unsupported Node Version: Trying v0.8.12 Compatability
[Error: Module version mismatch. Expected 11, got 1.]

It looks like it's in nodefly-gcinfo. I took a peek and saw a huge version lookup table, seems rather unmaintainable.

**Comment by themitchy** [comment]
Hey @bjornstar,

We're looking into the gcinfo module.  In the meantime we've push out nodefly@0.1.31 which will handle the error more gracefully [read: not crash].  The GC data on the NodeFly dashboard will not get populated using node@0.10 for now.

**Comment by bjornstar** [comment]
"memwatch": "~0.1" is not compatible with node v0.10

memwatch v0.2.2 is what you need for v0.10. -- https://github.com/lloyd/node-memwatch/pull/27

Is there a reason you're using v0.1?

More problems:

```
node_modules/nodefly/lib/tiers.js:15
    data._ts = nf.millis();
                  ^
TypeError: Cannot call method 'millis' of undefined
    at Timer.<anonymous> (node_modules/nodefly/lib/tiers.js:15:16)
    at Timer.timer.ontimeout (timers.js:242:14)
```

**Comment by bjornstar** [comment]
The node module doesn't complain anymore as of v0.1.33, but I'm not seeing any data on my dashboard.

Some communication about progress towards v0.10 support would be most welcome.

**Comment by themitchy** [comment]
Hey @bjornstar ,

Looks like you apps were reporting for a while but haven't been so the stale records were cleared out.  If you restart it and leave it running I can check in on what data it is reporting and why you might not be seeing it on the dashboard.

**Comment by themitchy** [comment]
0.10 supported for some time now in strong-agent@latest.  Closing.
