### ISSUE TITLE
Nodefly v0.1.31 throws error Cannot find module 'nodefly-gcinfo'

### ISSUE THREAD

**Issue by jesseditson** [NodeFly/NodeFly#21]
When starting an app with the latest nodefly, nodefly-gcinfo cannot be included - I see it listed as an installed dependency in npm list, but it appears to fail to include.

Reproduce:

```
npm install nodefly@0.1.31

echo "require('nodefly')" >> test.js
node test.js
```

Environments:

Mac OS Lion (latest)
Heroku

Fixes:

For now, `npm remove nodefly && npm install --save nodefly@0.1.29` seems to work.

**Comment by themitchy** [comment]
Hey @jesseditson,

0.1.31 was un-published and re-published with a fix a few minutes ago.  You're too fast for us! :-)

Thanks for the heads up!

**Comment by jesseditson** [comment]
Cool! If anyone runs across this issue and still hits the error, you can force npm to get the latest by doing:

```
npm cache clean nodefly && npm remove nodefly && npm install nodefly
```
