### ISSUE TITLE
server.connections is deprecated in node v0.10

### ISSUE THREAD

**Issue by bjornstar** [NodeFly/NodeFly#23]
https://github.com/joyent/node/pull/4595

lib/info.js:line 72
nf.metric(processScope, 'Connections', [nf.server_obj.connections,tp], '');

**Comment by themitchy** [comment]
Hey @bjornstar,

We're going to be taking a pass at updating how we calculate connections anyways.  Thanks for the heads up!

**Comment by HughePaul** [comment]
Hi, I noticed this popping up still. 

Trace: connections property is deprecated. Use getConnections() method
    at Server.deprecated (as connections) (util.js:71:17)
    at connectionInfo (node_modules/nodefly/lib/info.js:72:56)

**Comment by sprice** [comment]
This is still an issue. I was thinking with the Strongloop acquisition we may be able to stop running our fork of nodefly.js but I guess we'll have to wait a little while longer.

**Comment by themitchy** [comment]
Nope @sprice, the acquisition did not magically make our bug list disappear ;-) but we're still working hard to improve things.

I'll see if I can move this up the list - it's not been critical because it doesn't actually stop anything from working.

**Comment by themitchy** [comment]
This got fixed a couple weeks ago. My bad for not updating the issue.
