### ISSUE TITLE
Dont see any data reported

### ISSUE THREAD

**Issue by yurynix** [NodeFly/NodeFly#24]
Hi,
I'm running node 0.10.1 on FreeBSD 9, 
the server shows up in the dashboard, but there's no data displayed at all. =(

Is FreeBSD or node 0.10.1 is not supported?

**Comment by AndrewMartens** [comment]
Your account is showing data on the dashboard, so it should be working fine.  There is no information for CPU Usage or the V8 GC on FreeBSD for the moment, but otherwise our testing has shown that our Agent does work on FreeBSD using node 0.10.1.

**Comment by yurynix** [comment]
12 hours ago, when i just signuped it didnt showed any data for half hour,
It made me think it doesnt work, but then it showed the data after few hours so all ok.

Checked it again now, now it started to show data after few mins.
