### ISSUE TITLE
Can't see any data

### ISSUE THREAD

**Issue by avlakin** [NodeFly/NodeFly#25]
I set up monitoring last night. It seemed to work ok on my local machine. 

Once I deployed to EC2 I was no longer able to get data. 

My account is alakin.

I'm using Node v0.8.15 & Express@3.0.3

**Comment by Meekohi** [comment]
I setup monitoring a couple weeks ago, and it worked fine for about a week, but for the past few days have had the same problem.

Heroku; Node 0.8.20; Express 3.1.0

**Comment by constantx** [comment]
I'm going to nodefly dashboard via the heroku addons, but landed on `http://apm.nodefly.com/#dashboard` with an empty page :cry:

**Comment by constantx** [comment]
inspect the site yield

```
Uncaught Error: Load timeout for modules: text!templates/tooltips/externalCalls.html_unnormalized22,text!templates/tooltips/externalCalls.html,text!templates/account/pendingInvites.html
http://requirejs.org/docs/errors.html#timeout require-jquery.js:1803
```
