### ISSUE TITLE
CPU Info Not Displayed on Nodejitsu

### ISSUE THREAD

**Issue by groundwater** [NodeFly/NodeFly#3]

**Comment by sberryman** [comment]
Thanks, watching this issue now

**Comment by groundwater** [comment]
Try requiring `nodefly@0.1.10`

**Comment by sberryman** [comment]
does not appear to be pulling in cpu info but I don't see any errors...

UPDATE: Event loop doesn't look like it is showing any data either. (it was working before but then again there might not be any data to track here)
Top functions, heap size, concurrent connections and avg. response time by tier are working though

**Comment by groundwater** [comment]
@sberryman I have tried deploying an application to NodeJitsu, and I get CPU data, but the data is all zero. I would like to confirm in you see this as well, since it points to a different issue under the hood.

If you mouse over the CPU Usage graph, if you see a popup graph with _any_ data, even zero data then the app is indeed collecting CPU data, however it's somehow getting incorrect data.

**Comment by sberryman** [comment]
I've pulled NodeFly from my apps until there is a better way to manage the
instances I am monitoring. I push code updates several times a day and the
data just wasn't very valuable to me with a new hostname showing up for
every deploy.

On Tue, Nov 13, 2012 at 9:24 AM, Jacob Groundwater <notifications@github.com

**Comment by groundwater** [comment]
I'm gonna close this issue, but will mention that the hostname issue has been fixed in the latest version of the agent. There is a Nodejitsu example in the Howto.

**Comment by aeosynth** [comment]
I can confirm that CPU usage shows all zeros on Nodejitsu.
