### ISSUE TITLE
cpuProf is not defined

### ISSUE THREAD

**Issue by Morriz** [NodeFly/NodeFly#35]
Hi, I get an error using strongloop node (1.1) with strong-agent:

[ 'ReferenceError: cpuProf is not defined',
     '    at Transport.<anonymous> (bla/node_modules/strong-agent/lib/nodefly.js:166:3)',
     '    at Transport.EventEmitter.emit (events.js:95:17)',
     '    at Stream.<anonymous> (bla/node_modules/strong-agent/node_modules/uhura/lib/send_emitter.js:97:11)',
     '    at Stream.EventEmitter.emit (events.js:95:17)',
     '    at drain (bla/node_modules/strong-agent/node_modules/uhura/node_modules/JSONStream/node_modules/through/index.js:35:16)',
     '    at Stream.stream.queue.stream.push (bla/node_modules/strong-agent/node_modules/uhura/node_modules/JSONStream/node_modules/through/index.js:41:5)',
     '    at Parser.parser.onValue (bla/node_modules/strong-agent/node_modules/uhura/node_modules/JSONStream/index.js:75:12)',
     '    at Parser.proto.emit (§bla/node_modules/strong-agent/node_modules/uhura/node_modules/JSONStream/node_modules/jsonparse/jsonparse.js:326:8)',
     '    at Parser.proto.pop (bla/node_modules/strong-agent/node_modules/uhura/node_modules/JSONStream/node_modules/jsonparse/jsonparse.js:321:8)',
     '    at Parser.proto.onToken [as _onToken](bla/node_modules/strong-agent/node_modules/uhura/node_modules/JSONStream/node_modules/jsonparse/jsonparse.js:392:12)' ]

**Comment by themitchy** [comment]
Fixed in the latest strong-agent.
