### ISSUE TITLE
"Event Loop" section not working on some platforms

### ISSUE THREAD

**Issue by supermonster** [NodeFly/NodeFly#5]
The UI says the agent is out of date for "Event Loop" section even when the latest npm package was installed.

**Comment by kenpratt** [comment]
Neither my development nor production environments seems to ship data to that widget:
nodefly version 0.1.13, node v0.8.10, OS X 10.8.2 x86_64
nodefly version 0.1.13, node v0.8.6, Ubuntu 11.10 x86_64 on EC2

**Comment by kenpratt** [comment]
Works like a charm now, thanks! I assume you fixed something on your end?

**Comment by groundwater** [comment]
@kenpratt it was a javascript error in the chart UI, but if anyone asks... solar flares

**Comment by kenpratt** [comment]
Awesome, thanks :)
