### ISSUE TITLE
"could not parse ps data" console log after running for a few hours

### ISSUE THREAD

**Issue by deepwell** [NodeFly/NodeFly#6]
My node server starts outputting these messages after running for 4 hours.

could not parse ps data:     UTIME      TIME     ELAPSED
  0:14.92   0:21.13 01-00:00:34

could not parse ps data:     UTIME      TIME     ELAPSED
  0:14.93   0:21.15 01-00:01:34

could not parse ps data:     UTIME      TIME     ELAPSED
  0:14.94   0:21.17 01-00:02:34

could not parse ps data:     UTIME      TIME     ELAPSED
  0:14.95   0:21.19 01-00:03:34

could not parse ps data:     UTIME      TIME     ELAPSED
  0:14.97   0:21.21 01-00:04:34

could not parse ps data:     UTIME      TIME     ELAPSED
  0:14.98   0:21.23 01-00:05:34

Please make it stop, thanks!

Restarting the server makes it go away for awhile.

**Comment by groundwater** [comment]
I have removed the console output, but have not yet fixed the underlying issue. If you like, you can update to `nodefly@0.1.14a` in the mean time. It looks like there are some issues collecting CPU data on OS X.

I'll push out the fix as soon as possible.
