### ISSUE TITLE
Dependancies cannot compile on solaris

### ISSUE THREAD

**Issue by deepwell** [NodeFly/NodeFly#7]
Nodefly kills my server on start because:
[NodeFly] Timekit Module is Not Installed

Installing the latest stable version of nodefly is no good either because:

make: Entering directory `/home/node/node-service/releases/2012-11-23T19-15-22.641270899/node_modules/nodefly/node_modules/memwatch/build'
  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
cc1plus: error: unrecognized command line option "-fno-tree-vrp"
make: *** [Release/obj.target/memwatch/src/heapdiff.o] Error 1
make: Leaving directory`/home/node/node-service/releases/2012-11-23T19-15-22.641270899/node_modules/nodefly/node_modules/memwatch/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/v0.8.8/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! System SunOS 5.11
gyp ERR! command "node" "/opt/nodejs/v0.8.8/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/node-service/releases/2012-11-23T19-15-22.641270899/node_modules/nodefly/node_modules/memwatch
gyp ERR! node -v v0.8.8
gyp ERR! node-gyp -v v0.6.7
gyp ERR! not ok 
npm WARN optional dep failed, continuing memwatch@0.1.5
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
make: Entering directory `/home/node/node-service/releases/2012-11-23T19-15-22.641270899/node_modules/nodefly/node_modules/timekit/build'
  CXX(target) Release/obj.target/timekit/src/profiler.o
cc1plus: error: unrecognized command line option "-fno-tree-vrp"
make: *** [Release/obj.target/timekit/src/profiler.o] Error 1
make: Leaving directory`/home/node/node-service/releases/2012-11-23T19-15-22.641270899/node_modules/nodefly/node_modules/timekit/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/v0.8.8/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! System SunOS 5.11
gyp ERR! command "node" "/opt/nodejs/v0.8.8/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR!npm http GET https://registry.npmjs.org/zeparser/0.0.5
 cwd /home/node/node-service/releases/2012-11-23T19-15-22.641270899/node_modules/nodefly/node_modules/timekit
gyp ERR! node -v v0.8.8
gyp ERR! node-gyp -v v0.6.7
gyp ERR! not ok 
npm WARN optional dep failed, continuing timekit@0.1.8

sadness :(

**Comment by groundwater** [comment]
Hi @deepwell unfortunately timekit and memwatch are finicky about which platforms they install on. We actually have those listed as optional dependencies for that very reason. As such the nodefly agent should still install, and it appears like it does from your error message.

If the agent is crashing the server, it may be a bug where our agent behaved badly depending on how Solaris boxes report their platform names.

I _just_ marked a version of the agent as stable that omits the platform check, and may fix the issue you were having.

**Comment by deepwell** [comment]
Looks good, feel free to close.
